### ISSUE TITLE
How do I new up the implementation?

### ISSUE THREAD

**Issue by ghuntley** [benaadams/Ben.DictionarySlim#2]
The repository seems to be missing critical information from `README.md` and _an actual implementation_

**Comment by benaadams** [comment]
Tough crowd 😄

**Comment by benaadams** [comment]
Its taking me a while to get the directory structure right...

**Comment by benaadams** [comment]
Preview of a non-generic version here https://github.com/JamesNK/Newtonsoft.Json/pull/1413

**Comment by benaadams** [comment]
Initial implementation is in

**Comment by ghuntley** [comment]
Wait this is a legit thing? 😆
